# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20160526_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('default_value', models.IntegerField()),
                ('step_value', models.IntegerField()),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('is_percent', models.BooleanField(default=False)),
                ('parent', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
