# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='step_value',
            new_name='step',
        ),
    ]
