# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20160603_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='current_value',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
