# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='shop.Panel'),
        ),
    ]
