# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20160605_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='raw_data',
            field=models.FilePathField(default=1, path=b'/media/raw_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataview',
            name='transformed_data',
            field=models.FilePathField(default=1, path=b'/media/transformed_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='data_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_view_analyses', to='shop.DataView'),
        ),
    ]
