# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20160607_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BEN_ID', models.CharField(max_length=200)),
                ('CLM_ID', models.CharField(max_length=200)),
                ('SEGMENT', models.CharField(max_length=200)),
                ('CLM_FROM_DT', models.CharField(max_length=200)),
                ('CLM_THRU_DT', models.CharField(max_length=200)),
                ('PRVDR_NUM', models.CharField(max_length=200)),
                ('CLM_PMT_AMT', models.CharField(max_length=200)),
                ('NCH_PRMRY_PYR_CLM_PD_AMT', models.CharField(max_length=200)),
                ('AT_PHYSN_NPI', models.CharField(max_length=200)),
                ('OP_PHYSN_NPI', models.CharField(max_length=200)),
                ('OT_PHYSN_NPI', models.CharField(max_length=200)),
                ('CLM_ADMSN_DT', models.CharField(max_length=200)),
                ('ADMTNG_ICD9_DGNS_CD', models.CharField(max_length=200)),
                ('CLM_PASS_THRU_PER_DIEM_AMT', models.CharField(max_length=200)),
                ('NCH_BENE_IP_DDCTBL_AMT', models.CharField(max_length=200)),
                ('NCH_BENE_PTA_COINSRNC_LBLTY_AM', models.CharField(max_length=200)),
                ('NCH_BENE_BLOOD_DDCTBL_LBLTY_AM', models.CharField(max_length=200)),
                ('CLM_UTLZTN_DAY_CNT', models.CharField(max_length=200)),
                ('NCH_BENE_DSCHRG_DT', models.CharField(max_length=200)),
                ('CLM_DRG_CD', models.CharField(max_length=200)),
            ],
        ),
    ]
