# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_hospitalstay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataframe',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
