# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20160608_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataview',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='dataview',
            name='row_range_high',
        ),
        migrations.RemoveField(
            model_name='dataview',
            name='row_range_low',
        ),
        migrations.RemoveField(
            model_name='dataview',
            name='transformed_data',
        ),
        migrations.AddField(
            model_name='datatransformation',
            name='dataview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='shop.DataView'),
        ),
    ]
