# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20160608_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatransformation',
            name='feature',
            field=models.CharField(default='CLM_FROM_DT', max_length=200),
            preserve_default=False,
        ),
    ]
