# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_datatransformation_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdowns', to='shop.Panel')),
            ],
        ),
    ]
