# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_panel_result_function'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='result_function',
            new_name='result_function_name',
        ),
    ]
