# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20160610_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='type',
            field=models.CharField(choices=[(b'slider', b'Slider'), (b'single_dropdown', b'Single Dropdown'), (b'multiple_dropdown', b'Multiple Dropdown')], default=b'slider', max_length=200),
        ),
    ]
