# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20160610_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='result_function_name',
            field=models.CharField(choices=[(b'histogram', b'Histogram'), (b'scatterplot', b'Scatterplot'), (b'heatmap', b'Heatmap'), (b'network', b'Network')], default=b'histogram', max_length=200),
        ),
    ]
